<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Lunaticn</RootNamespace>
    <AssemblyName>LUNATICN</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CodePage>65001</CodePage>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Using Include="System.IO" />
    <Using Include="System.Net.Http" />
  </ItemGroup>
</Project>
